hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "36ffd9dc085d529a7e60e1276d73ae5a030b020313e6c5408593a6ae2af39673"

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "407fd025c6912135c7d40c238bb96fe05ea8172c403a100ed86f978fc8124c81"
metafile = true

